<?php
/**
 * .htaccess generator for the local delivery cache-miss routing.
 *
 * Generates Apache rewrite rules that:
 * - Serve existing cache files directly (static, no PHP).
 * - On cache miss, rewrite to oxpulse-img.php (the self-contained
 *   miss-endpoint).
 * - Gate WebP delivery on Accept: image/webp.
 * - Deny PHP execution inside the cache dir (defense-in-depth).
 * - Set immutable Cache-Control on cache files.
 *
 * Modeled on WebP-Express "Realizer" Variant-1 + Converter for Media
 * passthru patterns. The capability-test (CapabilityTester) determines
 * whether these rules can be trusted at runtime; if not, the
 * FallbackRewriter output-buffer path is used instead.
 *
 * @package OXPulse\Imager\Infrastructure\Local
 * @copyright Copyright (c) 2026 Anatoly Koptev
 * @license GPL-2.0-or-later
 */

declare(strict_types=1);

namespace OXPulse\Imager\Infrastructure\Local;

final class HtaccessGenerator
{
    /**
     * Generate the .htaccess rules for the cache directory.
     *
     * @param string $cacheBaseUrl The cache base URL (e.g.
     *        https://example.com/wp-content/cache/oxpulse).
     * @param string $endpointRelPath The endpoint path relative to
     *        wp-content/ (e.g. 'oxpulse-img.php').
     * @return string The .htaccess content.
     */
    public function generate(string $cacheBaseUrl, string $endpointRelPath): string
    {
        return <<<HTACCESS
# OXPulse Imager — local delivery cache routing (auto-generated).
# DO NOT EDIT — regenerated by the plugin on settings save.

# Deny PHP execution inside the cache dir (defense-in-depth —
# cache files must be served as static only).
php_flag engine off
RemoveHandler .php .phtml .phar

# Long immutable cache for existing cache files.
<IfModule mod_headers.c>
  Header set Cache-Control "public, max-age=31536000, immutable"
  Header set Vary "Accept"
</IfModule>

# Rewrite engine for cache-miss routing.
<IfModule mod_rewrite.c>
  RewriteEngine On

  # Only rewrite if the requested cache file does NOT exist.
  RewriteCond %{REQUEST_FILENAME} !-f

  # Only serve WebP to clients that accept it.
  RewriteCond %{HTTP_ACCEPT} image/webp

  # Rewrite the missing cache file to the miss-endpoint.
  # The endpoint resolves the key from the requested path basename.
  RewriteRule ^wp-content/cache/oxpulse/(.+)$ ../{$endpointRelPath} [L,QSA]
</IfModule>
HTACCESS;
    }
}
