<?php
/**
 * .htaccess generator for the local delivery cache-miss routing.
 *
 * Generates Apache rewrite rules that:
 * - Serve existing cache files directly (static, no PHP).
 * - On cache miss, rewrite to oxpulse-img.php (the self-contained
 *   miss-endpoint) for ALL clients — the Accept gate lives in the
 *   endpoint, which serves the ORIGINAL image to non-webp clients
 *   (issue #42, Option A; WebP-Express fail:'original'-style).
 * - Deny PHP execution inside the cache dir (defense-in-depth).
 * - Set immutable Cache-Control on cache files.
 *
 * Modeled on WebP-Express "Realizer" Variant-1 + Converter for Media
 * passthru patterns. The capability-test (CapabilityTester) determines
 * whether these rules can be trusted at runtime; if not, the
 * FallbackRewriter output-buffer path is used instead.
 *
 * @package OXPulse\Imager\Infrastructure\Local
 * @copyright Copyright (c) 2026 Anatoly Koptev
 * @license GPL-2.0-or-later
 */

declare(strict_types=1);

namespace OXPulse\Imager\Infrastructure\Local;

final class HtaccessGenerator
{
    /**
     * Generate the .htaccess rules for the cache directory.
     *
     * The file is written INTO the cache dir (wp-content/cache/oxpulse/),
     * a per-directory context: mod_rewrite strips the directory prefix
     * before matching, so the rule sees the path RELATIVE to the cache
     * dir (e.g. "<sourceHash>/<key>.webp"), NOT the docroot-relative
     * path. Historically the rule pattern was docroot-relative
     * (`^wp-content/cache/oxpulse/(.+)$`) and never matched here → every
     * cache-miss 404'd (issue #40). It now matches the dir-relative
     * trailing segment and forwards the signed key to the endpoint as
     * `?k=<key>` — the endpoint re-derives the sourceHash + format from
     * the signed payload, so the query form is sufficient and avoids
     * PATH_INFO / AcceptPathInfo portability differences across hosts.
     *
     * @param string $cacheBaseUrl The cache base URL (e.g.
     *        https://example.com/wp-content/cache/oxpulse). Used to
     *        derive the endpoint's absolute URL-path (two levels up)
     *        so the rewrite target is correct for a subdirectory
     *        install, not a hardcoded '/wp-content/'.
     * @param string $endpointRelPath The endpoint path relative to
     *        wp-content/ (e.g. 'oxpulse-img.php').
     * @return string The .htaccess content.
     */
    public function generate(string $cacheBaseUrl, string $endpointRelPath): string
    {
        // Derive the endpoint's absolute URL-path from the cache base URL.
        // cacheBaseUrl path is .../wp-content/cache/oxpulse → the endpoint
        // lives two levels up at .../wp-content/oxpulse-img.php.
        $cachePath = (string) parse_url($cacheBaseUrl, PHP_URL_PATH);
        if ($cachePath === '') {
            $cachePath = '/wp-content/cache/oxpulse';
        }
        $wpContentPath = dirname($cachePath, 2);
        if ($wpContentPath === '.' || $wpContentPath === '/') {
            $wpContentPath = '';
        }
        $endpointUrlPath = rtrim($wpContentPath, '/') . '/' . ltrim($endpointRelPath, '/');

        return <<<HTACCESS
# OXPulse Imager — local delivery cache routing (auto-generated).
# DO NOT EDIT — regenerated by the plugin on settings save.

# Deny script execution inside the cache dir (defense-in-depth). The
# `php_flag engine off` directive is Apache mod_php ONLY (silently
# ignored under php-fpm, the modern default), so gate with FilesMatch +
# type stripping instead — modelled on the industry-standard cache-dir
# hardening (WebP Express uses AddType + SanityCheck; we add an explicit
# deny). This is NOT the security boundary: the real guard is the
# HMAC-signed-key + webp-format-allowlist invariant in MissEndpointHandler
# (the cache dir only ever holds signed <key>.webp files; a forged or
# non-webp key is rejected before any disk write). nginx hosts do not
# read .htaccess — see the README nginx snippet.
<FilesMatch "\.(?i:php|phtml|php3|php4|php5|php7|phar|pht)$">
  <IfModule mod_authz_core.c>
    Require all denied
  </IfModule>
  <IfModule !mod_authz_core.c>
    Order deny,allow
    Deny from all
  </IfModule>
</FilesMatch>
<IfModule mod_mime.c>
  AddType image/webp .webp
  RemoveType .php .phtml .phar
</IfModule>

# Long immutable cache for existing cache files.
<IfModule mod_headers.c>
  Header set Cache-Control "public, max-age=31536000, immutable"
  Header set Vary "Accept"
</IfModule>

# Rewrite engine for cache-miss routing.
<IfModule mod_rewrite.c>
  RewriteEngine On

  # Only rewrite if the requested cache file does NOT exist.
  RewriteCond %{REQUEST_FILENAME} !-f

  # Cache miss: forward the signed key (the trailing "<key>.webp"
  # segment, minus the extension) to the miss-endpoint as ?k=<key>.
  # Matched dir-relative (see the class docblock); the endpoint
  # re-derives sourceHash + format from the signed payload.
  RewriteRule ([^/]+)\.webp$ {$endpointUrlPath}?k=$1 [L,QSA]
</IfModule>
HTACCESS;
    }
}
