<?php
/**
 * .htaccess generator for the local delivery cache-miss routing.
 *
 * Generates Apache rewrite rules that:
 * - Serve existing cache files directly (static, no PHP).
 * - On cache miss, rewrite to oxpulse-img.php (the self-contained
 *   miss-endpoint).
 * - Gate WebP delivery on Accept: image/webp.
 * - Deny PHP execution inside the cache dir (defense-in-depth).
 * - Set immutable Cache-Control on cache files.
 *
 * Modeled on WebP-Express "Realizer" Variant-1 + Converter for Media
 * passthru patterns. The capability-test (CapabilityTester) determines
 * whether these rules can be trusted at runtime; if not, the
 * FallbackRewriter output-buffer path is used instead.
 *
 * @package OXPulse\Imager\Infrastructure\Local
 * @copyright Copyright (c) 2026 Anatoly Koptev
 * @license GPL-2.0-or-later
 */

declare(strict_types=1);

namespace OXPulse\Imager\Infrastructure\Local;

final class HtaccessGenerator
{
    /**
     * Generate the .htaccess rules for the cache directory.
     *
     * The file is written INTO the cache dir (wp-content/cache/oxpulse/),
     * a per-directory context: mod_rewrite strips the directory prefix
     * before matching, so the rule sees the path RELATIVE to the cache
     * dir (e.g. "<sourceHash>/<key>.webp"), NOT the docroot-relative
     * path. Historically the rule pattern was docroot-relative
     * (`^wp-content/cache/oxpulse/(.+)$`) and never matched here → every
     * cache-miss 404'd (issue #40). It now matches the dir-relative
     * trailing segment and forwards the signed key to the endpoint as
     * `?k=<key>` — the endpoint re-derives the sourceHash + format from
     * the signed payload, so the query form is sufficient and avoids
     * PATH_INFO / AcceptPathInfo portability differences across hosts.
     *
     * @param string $cacheBaseUrl The cache base URL (e.g.
     *        https://example.com/wp-content/cache/oxpulse). Used to
     *        derive the endpoint's absolute URL-path so the rewrite
     *        target is correct regardless of the site's wp-content
     *        location.
     * @param string $endpointRelPath The endpoint path relative to
     *        wp-content/ (e.g. 'oxpulse-img.php').
     * @return string The .htaccess content.
     */
    public function generate(string $cacheBaseUrl, string $endpointRelPath): string
    {
        // Derive the endpoint's absolute URL-path from the cache base URL.
        // cacheBaseUrl path is .../wp-content/cache/oxpulse → the endpoint
        // lives two levels up at .../wp-content/oxpulse-img.php.
        $cachePath = (string) parse_url($cacheBaseUrl, PHP_URL_PATH);
        if ($cachePath === '' || $cachePath === false) {
            $cachePath = '/wp-content/cache/oxpulse';
        }
        $wpContentPath = dirname($cachePath, 2);
        if ($wpContentPath === '.' || $wpContentPath === DIRECTORY_SEPARATOR) {
            $wpContentPath = '';
        }
        $endpointUrlPath = rtrim($wpContentPath, '/') . '/' . ltrim($endpointRelPath, '/');

        return <<<HTACCESS
# OXPulse Imager — local delivery cache routing (auto-generated).
# DO NOT EDIT — regenerated by the plugin on settings save.

# Deny PHP execution inside the cache dir (defense-in-depth —
# cache files must be served as static only).
#
# CAVEAT: `php_flag engine off` is Apache mod_php ONLY. Under php-fpm
# (the modern default) it is silently ignored, and under
# `AllowOverride None` the whole .htaccess is ignored. It is kept as
# defense-in-depth for mod_php hosts but is NOT the security boundary.
# The real guard is the signed-key + format-allowlist invariant in
# MissEndpointHandler: the cache dir only ever contains
# <key>.webp files (key = HMAC-signed, format allowlisted to webp),
# so an attacker cannot plant an executable-named file even with a
# compromised signing key — the signature check rejects it. nginx
# hosts must use the try_files snippet in the README nginx section
# (this .htaccess is never read by nginx).
php_flag engine off
RemoveHandler .php .phtml .phar

# Long immutable cache for existing cache files.
<IfModule mod_headers.c>
  Header set Cache-Control "public, max-age=31536000, immutable"
  Header set Vary "Accept"
</IfModule>

# Rewrite engine for cache-miss routing.
<IfModule mod_rewrite.c>
  RewriteEngine On

  # Only rewrite if the requested cache file does NOT exist.
  RewriteCond %{REQUEST_FILENAME} !-f

  # Only serve WebP to clients that accept it.
  RewriteCond %{HTTP_ACCEPT} image/webp

  # Cache miss: forward the signed key (the trailing "<key>.webp"
  # segment, minus the extension) to the miss-endpoint as ?k=<key>.
  # Matched dir-relative (see the class docblock); the endpoint
  # re-derives sourceHash + format from the signed payload.
  RewriteRule ([^/]+)\.webp$ {$endpointUrlPath}?k=$1 [L,QSA]
</IfModule>
HTACCESS;
    }
}
