<?php
/**
 * Self-contained miss-endpoint file generator (Phase 6, Dispatch 2).
 *
 * Generates the oxpulse-img.php file into wp-content/ at activation /
 * settings-save time. The file is self-contained: it requires the
 * composer autoloader (NOT wp-load.php) and bakes the needed config
 * as PHP constants at write-time. This avoids the WP bootstrap tax
 * per image request (the CfM webpc-passthru.php / WebP-Express wod/
 * pattern).
 *
 * The signing key + salt are baked as base64-encoded constants and
 * base64_decoded at runtime — the raw binary secret never appears in
 * the file source. The file is PHP, not served as text, so the
 * constants are not web-readable; the base64 encoding is an extra
 * defense-in-depth layer.
 *
 * @package OXPulse\Imager\Infrastructure\Local
 * @copyright Copyright (c) 2026 Anatoly Koptev
 * @license GPL-2.0-or-later
 */

declare(strict_types=1);

namespace OXPulse\Imager\Infrastructure\Local;

final class MissEndpointGenerator
{
    /**
     * Generate the self-contained oxpulse-img.php endpoint file.
     *
     * @param string $outputFile Absolute path to write (e.g.
     *        wp-content/oxpulse-img.php).
     * @param string $signingKey Raw binary signing key.
     * @param string $signingSalt Raw binary signing salt.
     * @param string $uploadsBasedir Absolute uploads base directory.
     * @param string $uploadsBaseurl Uploads base URL (scheme+host+path).
     * @param string $cacheDir Absolute cache directory.
     * @param string $autoloaderPath Absolute path to vendor/autoload.php.
     * @return string The path written (same as $outputFile).
     */
    public function generate(
        string $outputFile,
        string $signingKey,
        string $signingSalt,
        string $uploadsBasedir,
        string $uploadsBaseurl,
        string $cacheDir,
        string $autoloaderPath,
    ): string {
        $keyB64 = base64_encode($signingKey);
        $saltB64 = base64_encode($signingSalt);

        $php = <<<PHP
<?php
/**
 * OXPulse Imager — local delivery miss-endpoint (auto-generated).
 *
 * Self-contained: no WordPress bootstrap. Requires the composer autoloader +
 * bakes config as constants. Handles cache-miss requests for
 * /wp-content/cache/oxpulse/<sourceHash>/<key>.<fmt>.
 *
 * DO NOT EDIT — regenerated by the plugin on settings save.
 */

declare(strict_types=1);

// Baked configuration (base64-encoded secrets, decoded at runtime).
define('OXPULSE_SIGNING_KEY', base64_decode('{$keyB64}'));
define('OXPULSE_SIGNING_SALT', base64_decode('{$saltB64}'));
define('OXPULSE_UPLOADS_BASEDIR', '{$uploadsBasedir}');
define('OXPULSE_UPLOADS_BASEURL', '{$uploadsBaseurl}');
define('OXPULSE_CACHE_DIR', '{$cacheDir}');

require_once '{$autoloaderPath}';

use OXPulse\Imager\Domain\Config\SigningConfig;
use OXPulse\Imager\Infrastructure\Image\WebpTransformer;
use OXPulse\Imager\Infrastructure\Local\LocalBackend;
use OXPulse\Imager\Infrastructure\Local\MissEndpointHandler;
use OXPulse\Imager\Infrastructure\Local\MissEndpointResponse;
use OXPulse\Imager\Infrastructure\Local\PathGuard;

// Resolve the cache key: from ?k= (fallback mode) or from the
// requested cache path basename (<key>.<fmt>).
\$key = isset(\$_GET['k']) ? \$_GET['k'] : '';
\$format = 'webp';
\$accept = \$_SERVER['HTTP_ACCEPT'] ?? '';

if (\$key === '' && isset(\$_SERVER['REQUEST_URI'])) {
    // Apache rewrite: the requested path is the cache file path.
    \$basename = basename(\$_SERVER['REQUEST_URI']);
    \$dotPos = strrpos(\$basename, '.');
    if (\$dotPos !== false) {
        \$key = substr(\$basename, 0, \$dotPos);
        \$format = substr(\$basename, \$dotPos + 1);
    }
}

if (\$key === '') {
    http_response_code(400);
    exit;
}

\$signing = new SigningConfig(OXPULSE_SIGNING_KEY, OXPULSE_SIGNING_SALT);
\$backend = new LocalBackend(\$signing);
\$transformer = new WebpTransformer();
\$pathGuard = new PathGuard(OXPULSE_UPLOADS_BASEDIR, OXPULSE_UPLOADS_BASEURL);
\$handler = new MissEndpointHandler(
    backend: \$backend,
    transformer: \$transformer,
    pathGuard: \$pathGuard,
    cacheDir: OXPULSE_CACHE_DIR,
    uploadsBasedir: OXPULSE_UPLOADS_BASEDIR,
);

\$response = \$handler->handle(\$key, \$format, \$accept);

// Emit the response.
http_response_code(\$response->status);
header('Content-Type: ' . \$response->contentType);
foreach (\$response->headers as \$name => \$value) {
    header(\$name . ': ' . \$value);
}

if (\$response->body !== null) {
    echo \$response->body;
} elseif (\$response->filePath !== null) {
    // Stream the file (fail-safe original serving).
    readfile(\$response->filePath);
}
exit;

PHP;

        file_put_contents($outputFile, $php);
        return $outputFile;
    }
}
