<?php
/**
 * Self-contained miss-endpoint file generator (Phase 6, Dispatch 2).
 *
 * Generates the oxpulse-img.php file into wp-content/ at activation /
 * settings-save time. The file is self-contained: it bakes a MINIMAL
 * PSR-4 autoloader (the same shape as Plugin::registerAutoloader,
 * mapping OXPulse\Imager\ → the plugin src/ dir) and bakes the needed
 * config as PHP constants at write-time. This avoids the WP bootstrap
 * tax per image request (the CfM webpc-passthru.php / WebP-Express
 * wod/ pattern) AND avoids any vendor/ dependency — vendor/ is
 * export-ignored from the release ZIP (.gitattributes), and the plugin
 * has zero third-party runtime deps (composer.json require = php>=8.3
 * only). FIX #45: the previous version baked
 * `require_once vendor/autoload.php`, which 500'd on every wordpress.org
 * install (no vendor/ shipped) → the entire free tier was broken.
 *
 * The signing key + salt are baked as base64-encoded constants and
 * base64_decoded at runtime — the raw binary secret never appears in
 * the file source. The file is PHP, not served as text, so the
 * constants are not web-readable; the base64 encoding is an extra
 * defense-in-depth layer.
 *
 * @package OXPulse\Imager\Infrastructure\Local
 * @copyright Copyright (c) 2026 Anatoly Koptev
 * @license GPL-2.0-or-later
 */

declare(strict_types=1);

namespace OXPulse\Imager\Infrastructure\Local;

final class MissEndpointGenerator
{
    /**
     * Generate the self-contained oxpulse-img.php endpoint file.
     *
     * @param string $outputFile Absolute path to write (e.g.
     *        wp-content/oxpulse-img.php).
     * @param string $signingKey Raw binary signing key.
     * @param string $signingSalt Raw binary signing salt.
     * @param string $uploadsBasedir Absolute uploads base directory.
     * @param string $uploadsBaseurl Uploads base URL (scheme+host+path).
     * @param string $cacheDir Absolute cache directory.
     * @param string $srcDir Absolute path to the plugin src/ directory
     *        (the endpoint bakes a self-contained PSR-4 autoloader
     *        mapping OXPulse\Imager\ → this dir; NO vendor/ dependency).
     * @param int|null $avifQuality #47: per-format AVIF quality override
     *        from the admin formatQuality setting. Baked as a constant
     *        (the endpoint has no WP option access). 0/null = use the
     *        payload's default quality for avif too.
     * @return string The path written (same as $outputFile).
     */
    public function generate(
        string $outputFile,
        string $signingKey,
        string $signingSalt,
        string $uploadsBasedir,
        string $uploadsBaseurl,
        string $cacheDir,
        string $srcDir,
        ?int $avifQuality = null,
    ): string {
        $keyB64 = base64_encode($signingKey);
        $saltB64 = base64_encode($signingSalt);

        // Escape every baked value via var_export() so ANY path (incl.
        // ones containing apostrophes — legit on some hosts) round-trips
        // safely inside a single-quoted PHP string literal. FIX #33:
        // raw interpolation broke the endpoint with a parse error when a
        // path contained an apostrophe. The base64 key/salt literals are
        // also var_exported for consistency (the base64 alphabet has no
        // apostrophes, so this is a no-op there but keeps the defense-
        // in-depth base64 layer intact — the raw binary secret never
        // appears in the file source).
        // phpcs:disable WordPress.PHP.DevelopmentFunctions.error_log_var_export -- var_export used for codegen (embed config as PHP literals), not debug.
        $keyConst   = var_export($keyB64, true);
        $saltConst  = var_export($saltB64, true);
        $basedirLit = var_export($uploadsBasedir, true);
        $baseurlLit = var_export($uploadsBaseurl, true);
        $cacheLit   = var_export($cacheDir, true);
        $srcDirLit  = var_export($srcDir, true);
        $avifQualityInt = $avifQuality ?? 0;
        // phpcs:enable

        $php = "<?php
/**
 * OXPulse Imager — local delivery miss-endpoint (auto-generated).
 *
 * Self-contained: no WordPress bootstrap, no third-party autoloader
 * dependency. Bakes a minimal PSR-4 autoloader (OXPulse\Imager\ → src/)
 * + bakes config as constants. Handles cache-miss requests for
 * /wp-content/cache/oxpulse/<sourceHash>/<key>.<fmt>.
 *
 * DO NOT EDIT — regenerated by the plugin on settings save.
 */

declare(strict_types=1);

// Baked configuration (base64-encoded secrets, decoded at runtime).
define('OXPULSE_SIGNING_KEY', base64_decode({$keyConst}));
define('OXPULSE_SIGNING_SALT', base64_decode({$saltConst}));
define('OXPULSE_UPLOADS_BASEDIR', {$basedirLit});
define('OXPULSE_UPLOADS_BASEURL', {$baseurlLit});
define('OXPULSE_CACHE_DIR', {$cacheLit});
define('OXPULSE_SRC_DIR', {$srcDirLit});
// #47: per-format AVIF quality override (0 = use the payload's default q).
define('OXPULSE_AVIF_QUALITY', {$avifQualityInt});

// Self-contained PSR-4 autoloader — mirrors Plugin::registerAutoloader().
// The release ZIP ships no third-party autoloader (the plugin has zero
// runtime deps), so the endpoint loads plugin classes directly from src/.
// FIX #45: the previous `require_once <autoloader>` 500'd on every
// wordpress.org install where the autoloader file was absent.
spl_autoload_register(static function (string \$class): void {
    \$prefix = 'OXPulse\\\\Imager\\\\';
    if (!str_starts_with(\$class, \$prefix)) {
        return;
    }
    \$relative = substr(\$class, strlen(\$prefix));
    \$relative = str_replace('\\\\', '/', \$relative);
    \$path = OXPULSE_SRC_DIR . '/' . \$relative . '.php';
    if (is_file(\$path)) {
        require_once \$path;
    }
});

use OXPulse\Imager\Domain\Config\SigningConfig;
use OXPulse\Imager\Infrastructure\Image\ImageTransformer;
use OXPulse\Imager\Infrastructure\Local\LocalBackend;
use OXPulse\Imager\Infrastructure\Local\MissEndpointHandler;
use OXPulse\Imager\Infrastructure\Local\MissEndpointResponse;
use OXPulse\Imager\Infrastructure\Local\PathGuard;

// Resolve the cache key + format: from ?k= (the bare endpoint path →
// 'auto' → server-side negotiation) or from the requested cache path
// basename (<key>.<fmt> — clean-URL path → explicit format).
\$key = isset(\$_GET['k']) ? \$_GET['k'] : '';
\$format = 'auto';
\$accept = \$_SERVER['HTTP_ACCEPT'] ?? '';

if (\$key === '' && isset(\$_SERVER['REQUEST_URI'])) {
    // Apache rewrite: the requested path is the cache file path.
    // #63 review: parse_url returns null for a path-less URI →
    // basename(null) is a PHP 8.3+ deprecation (and can corrupt the
    // binary body under bad display_errors). Guard with ?? ''.
    \$basename = basename(parse_url(\$_SERVER['REQUEST_URI'] ?? '', PHP_URL_PATH) ?? '');
    \$dotPos = strrpos(\$basename, '.');
    if (\$dotPos !== false) {
        \$key = substr(\$basename, 0, \$dotPos);
        \$ext = strtolower(substr(\$basename, \$dotPos + 1));
        // Only accept known image formats from the URL; anything else
        // stays 'auto' (the handler's allowlist rejects unknown exts).
        if (in_array(\$ext, ['webp', 'avif'], true)) {
            \$format = \$ext;
        }
    }
}

if (\$key === '') {
    http_response_code(400);
    exit;
}

\$signing = new SigningConfig(OXPULSE_SIGNING_KEY, OXPULSE_SIGNING_SALT);
\$backend = new LocalBackend(\$signing);
\$transformer = new ImageTransformer();
\$pathGuard = new PathGuard(OXPULSE_UPLOADS_BASEDIR, OXPULSE_UPLOADS_BASEURL);
\$handler = new MissEndpointHandler(
    backend: \$backend,
    transformer: \$transformer,
    pathGuard: \$pathGuard,
    cacheDir: OXPULSE_CACHE_DIR,
    uploadsBasedir: OXPULSE_UPLOADS_BASEDIR,
    avifQualityOverride: OXPULSE_AVIF_QUALITY > 0 ? OXPULSE_AVIF_QUALITY : null,
);

\$response = \$handler->handle(\$key, \$format, \$accept);

// Emit the response.
http_response_code(\$response->status);
header('Content-Type: ' . \$response->contentType);
foreach (\$response->headers as \$name => \$value) {
    header(\$name . ': ' . \$value);
}

if (\$response->body !== null) {
    echo \$response->body;
} elseif (\$response->filePath !== null) {
    // Stream the file (fail-safe original serving).
    readfile(\$response->filePath);
}
exit;
";

        // Atomic write: temp file in the same directory → chmod 0600 →
        // rename into place. FIX #30: a plain file_put_contents whose
        // return was unchecked silently "succeeded" on a failed write
        // (perms/disk-full), leaving the OLD signing key active on disk
        // while UrlRewriter signed with the NEW key → every image 400s.
        // The temp+rename ensures a partial/failed write NEVER replaces
        // a working endpoint. FIX #31: chmod 0600 so the baked signing
        // key is not world-readable on shared hosting (a co-tenant
        // reading it could forge signatures).
        $dir = dirname($outputFile);
        $temp = $dir . '/.oxpulse-img-' . getmypid() . '-' . bin2hex(random_bytes(4)) . '.tmp';

        $written = @file_put_contents($temp, $php);
        if ($written === false) {
            // phpcs:ignore WordPress.WP.AlternativeFunctions.unlink_unlink -- self-contained miss-endpoint runs without wp-load; WP filesystem wrappers unavailable.
            @unlink($temp);
            throw new \RuntimeException(
                'Failed to write miss-endpoint file: file_put_contents returned false'
                . ' (target: ' . $outputFile . '). Check directory permissions / disk space.'
            );
        }

        // Restrict to owner-only BEFORE the rename lands the baked key
        // at its final path. If chmod can't restrict (some hosts), log
        // a warning but proceed — the file is still PHP (not served as
        // text), and the base64 secret layer is defense-in-depth.
        // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_chmod -- self-contained miss-endpoint runs without wp-load; WP filesystem wrappers unavailable.
        if (!@chmod($temp, 0600)) {
            // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_error_log -- self-contained miss-endpoint runs without wp-load; no WP logger available, error_log is the only diagnostic sink.
            error_log(
                'oxpulse-imager: WARNING — could not chmod 0600 the generated'
                . ' miss-endpoint file (' . $outputFile . '). The baked signing'
                . ' key may be readable by co-tenants on shared hosting.'
            );
        }

        // phpcs:ignore WordPress.WP.AlternativeFunctions.rename_rename -- self-contained miss-endpoint runs without wp-load; WP filesystem wrappers unavailable.
        if (!@rename($temp, $outputFile)) {
            // phpcs:ignore WordPress.WP.AlternativeFunctions.unlink_unlink -- self-contained miss-endpoint runs without wp-load; WP filesystem wrappers unavailable.
            @unlink($temp);
            throw new \RuntimeException(
                'Failed to install miss-endpoint file: rename(' . $temp . ' -> '
                . $outputFile . ') failed. Check directory permissions / disk space.'
            );
        }

        return $outputFile;
    }
}
